services:
  cashflow:
    build:
      context: .
      dockerfile: Dockerfile
    command: > 
      bash -c  "pytest -v --disable-warnings &&
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8082"
    ports:
      - "8082:8082"
    volumes:
      - ./:/cashflow/cashflow/